- .github/workflows/ci-testing.yml
- .github/workflows/push.yml
- docker/docker-compose.yml
- docker/start.sh
Add a simple CI workflow for pull requests and push.
Currently only the stable version 2.9 of Netbox is used. This can be a matrix build for multiple supported versions later.
> Add CI workflow

- example/main.tf
- go.mod
- go.sum
- netbox/resource_netbox_ip_address.go
- netbox/resource_netbox_ip_address_test.go
> Allow to manage tenants of ip addresses

- CHANGELOG.md
- example/main.tf
- netbox/data_source_netbox_cluster_group.go
- netbox/data_source_netbox_cluster_group_test.go
- netbox/provider.go
- netbox/resource_netbox_cluster.go
- netbox/resource_netbox_cluster_group.go
- netbox/resource_netbox_cluster_group_test.go
- netbox/resource_netbox_cluster_test.go
Still missing data source and changes in related resources, e.g. cluster.
> Add cluster group resource

- netbox/data_source_netbox_virtual_machines.go
- netbox/data_source_netbox_virtual_machines_test.go
- netbox/provider.go
Add 'limit' to data_source_netbox_virtual_machines (I was hitting the default limit of 50 machines)
> Add 'limit' to data_source_netbox_virtual_machines

- netbox/resource_netbox_interface.go
- netbox/resource_netbox_interface_test.go
- website/docs/r/interface.md
> Add mac_address to netbox_interface resource

- .goreleaser.yml
> enable arm64 builds

- .github/workflows/ci-testing.yml
remove `pull_request` trigger and only use `push` trigger #89
> Fix duplicate builds

- netbox/data_source_netbox_vrf.go
- netbox/resource_netbox_vrf.go
- netbox/resource_netbox_vrf_test.go
Small patch to add tenant_id as supported parameter in vrf resource and data source
> Support tenant_id in vrf resource and data

- netbox/data_source_netbox_region.go
- netbox/data_source_netbox_region_test.go
- netbox/provider.go
- netbox/resource_netbox_region.go
- netbox/resource_netbox_region_test.go
- Resource netsim_region added
- Default Slug is the Name
- Support for parent region specification
- Data Source netsim_region added
- Filter for a single Region
- Tests for Resource and Data Source
> Add Support for creating and querying regions

- example/main.tf
- netbox/provider.go
- netbox/resource_netbox_device.go
- netbox/resource_netbox_device_test.go
- netbox/resource_netbox_device_type.go
- netbox/resource_netbox_device_type_test.go
- netbox/resource_netbox_manufacturer.go
- netbox/resource_netbox_manufacturer_test.go
Adds basic support for adding Netbox devices.
> Add netbox device resource

- netbox/provider.go
- netbox/resource_netbox_aggregate.go
- netbox/resource_netbox_aggregate_test.go
- netbox/resource_netbox_rir.go
- netbox/resource_netbox_rir_test.go
Adds Netbox Aggregate and RIR resource
> Add Aggregate and RIR support

- netbox/resource_netbox_ip_address.go
- netbox/resource_netbox_ip_address_test.go
> Add description attribute to netbox_ip_address resource

- netbox/provider.go
- netbox/resource_netbox_circuit.go
- netbox/resource_netbox_circuit_provider.go
- netbox/resource_netbox_circuit_provider_test.go
- netbox/resource_netbox_circuit_termination.go
- netbox/resource_netbox_circuit_termination_test.go
- netbox/resource_netbox_circuit_test.go
- netbox/resource_netbox_circuit_type.go
- netbox/resource_netbox_circuit_type_test.go
netbox_circuit
netbox_circuit_provider
netbox_circuit_termination
netbox_circuit_type
> Add various circuit resources

- netbox/resource_netbox_site.go
- netbox/resource_netbox_site_test.go
- netbox/util.go
Adds support for additional site resource fields
* timezone
* latitude
* longitude
* custom fields
Includes minor bug fix where site tags are not read because of missing statement
> Add site resource fields

- .github/workflows/ci-testing.yml
- .github/workflows/release.yml
- go.mod
- go.sum
> Use go 1.18

- netbox/data_source_netbox_ip_addresses.go
- netbox/data_source_netbox_ip_addresses_test.go
- Fix usage of wrong role attribute
- Add role for testcase
> 🐛 netbox_ip_addresses: Fix usage of wrong attribute

- netbox/resource_netbox_device.go
> Fix: Device ID set on update

- .github/workflows/ci-testing.yml
- CHANGELOG.md
- GNUmakefile
- docs/resources/virtual_machine.md
- netbox/provider.go
- netbox/resource_netbox_primary_ip_test.go
- netbox/resource_netbox_virtual_machine.go
- netbox/resource_netbox_virtual_machine_test.go
> Add status attribute to VM resource

- netbox/data_source_netbox_ip_addresses_test.go
- netbox/data_source_netbox_virtual_machines_test.go
- netbox/resource_netbox_circuit_termination.go
- netbox/resource_netbox_device.go
- netbox/resource_netbox_device_test.go
- netbox/resource_netbox_primary_ip.go
- netbox/resource_netbox_primary_ip_test.go
- netbox/resource_netbox_token.go
- netbox/resource_netbox_virtual_machine.go
- netbox/resource_netbox_virtual_machine_test.go
Have made the changes that passes the tests.
> 232 netbox 3.3

- .github/workflows/ci-testing.yml
- GNUmakefile
- docs/resources/circuit_termination.md
- docs/resources/device.md
- docs/resources/token.md
- docs/resources/virtual_machine.md
- go.mod
- go.sum
- netbox/data_source_netbox_virtual_machines_test.go
- netbox/resource_netbox_circuit_termination.go
- netbox/resource_netbox_custom_field.go
- netbox/resource_netbox_device.go
- netbox/resource_netbox_device_test.go
- netbox/resource_netbox_primary_ip.go
- netbox/resource_netbox_primary_ip_test.go
- netbox/resource_netbox_token.go
- netbox/resource_netbox_token_test.go
- netbox/resource_netbox_virtual_machine.go
- netbox/resource_netbox_virtual_machine_test.go
Draft for #232 to introduce Netbox 3.3 support and check what we have to fix afterwards to get compatibility.
Changelog of Netbox 3.3: https://github.com/netbox-community/netbox/releases/tag/v3.3.0
Todo:
> Netbox 3.3

- CHANGELOG.md
- netbox/data_source_netbox_prefix.go
Add description read-only attribute to netbox_prefix datasource
> Add description to netbox_prefix datasource

- docs/data-sources/prefix.md
- netbox/data_source_netbox_prefix.go
- netbox/data_source_netbox_prefix_test.go
Change description field properties in data source "netbox_prefix".
Add new tests to include description filter.
> Add data source filter by description field in netbox_prefix.

- docs/resources/device_type.md
- netbox/data_source_netbox_device_type.go
- netbox/resource_netbox_device_type.go
- netbox/resource_netbox_device_type_test.go
This PR adds the u_height value to the device type resource
> Add u_height

- docs/data-sources/cluster.md
- docs/resources/cluster.md
- netbox/data_source_netbox_cluster.go
- netbox/data_source_netbox_cluster_test.go
- netbox/resource_netbox_cluster.go
- netbox/resource_netbox_cluster_test.go
Adding new field (commtents) to the cluster resource.
> Feature: Add cluster comments field

- netbox/resource_netbox_virtual_machine.go
- netbox/resource_netbox_virtual_machine_test.go
Fix the ONE MISSING "&" required to make everything work.
> Fix VM Local Context - Incorrect Read and Update functions

- docs/data-sources/devices.md
- netbox/data_source_netbox_devices.go
- netbox/data_source_netbox_devices_test.go
> feat: Add tags to devices data source result

- docs/data-sources/site.md
- netbox/data_source_netbox_site.go
- netbox/data_source_netbox_site_test.go
> feat: Allow id as search parameter for site data source

- docs/data-sources/cluster.md
- netbox/data_source_netbox_cluster.go
- netbox/data_source_netbox_cluster_test.go
Add ability to get cluster by it's ID
retrieving custom fields of a cluster also
> Adding ability to get cluster by Id + retrieving cluster custom fields

- netbox/data_source_netbox_virtual_machines.go
- netbox/data_source_netbox_virtual_machines_test.go
- 🔧 Add tag filter
- ✅ Add tests for tag filter
>  🔧 Add tag filter for netbox_virtual_machines

- netbox/data_source_netbox_devices.go
- netbox/data_source_netbox_location.go
- netbox/data_source_netbox_location_test.go
- netbox/provider.go
Added netbox_location datasource
Added filtering by location_id and rack_id for netbox_device
> Added netbox_location datasource

- netbox/data_source_netbox_ip_addresses.go
- netbox/data_source_netbox_ip_addresses_test.go
> feat: add parent_prefix to filter

- docs/data-sources/devices.md
- netbox/data_source_netbox_devices.go
- netbox/data_source_netbox_devices_test.go
- netbox/resource_netbox_device_test.go
Adds the capability to use tags and status to filter for devices data resources. Adds also additional test cases to verify the functionality.
> Adds new tags and status filter for devices data resource

- GNUmakefile
- README.md
Since full suite of acceptance tests takes a long time to run I updated makefile with a command to run a single specific acceptance test.
> feat: run a single acceptance test

- netbox/data_source_netbox_devices_test.go
- netbox/data_source_netbox_ip_addresses_test.go
- netbox/data_source_netbox_tenants_test.go
- netbox/data_source_netbox_vrf_test.go
- netbox/resource_netbox_device_test.go
> Fix ci-testing pipeline

- docs/data-sources/cluster.md
- netbox/data_source_netbox_cluster.go
- netbox/data_source_netbox_cluster_test.go
Make it possible to filter clusters by cluster group.
> feat(cluster): support searching by cluster group

- docs/data-sources/virtual_machines.md
- netbox/data_source_netbox_virtual_machines.go
- netbox/data_source_netbox_virtual_machines_test.go
> feat: add platform slug to virtual machines data source output

- docs/resources/vlan_group.md
- netbox/resource_netbox_vlan_group.go
Simple PR to fix wrong valid values list in the docs for the resource `netbox_vlan_group`
> fix: error in 'netbox_vlan_group' doc

- netbox/resource_netbox_device_interface.go
- netbox/resource_netbox_device_interface_test.go
Simple PR to add the label field to device interfaces
> feat: add labels to device interfaces

- netbox/data_source_netbox_vlans.go
Added the ability to filter vlans by site_id
> feat: add a site_id filter for vlans

- .github/workflows/ci-testing.yml
Testing to see if the ci workflow works better with older ubuntu version
> Use ubuntu 22.04 for testing

- netbox/resource_netbox_site.go
- netbox/resource_netbox_site_test.go
This field has not been available so far
> Allow setting site comments

- netbox/resource_netbox_user.go
- netbox/resource_netbox_user_test.go
This adds more fields to the `netbox_user` resource which are manageable in the Netbox UI
> Manage more user fields

- docs/data-sources/device_interfaces.md
- docs/data-sources/locations.md
- docs/resources/group.md
- docs/resources/location.md
- docs/resources/site.md
- docs/resources/user.md
These docs changes were forgotten in previous PRs
> Add missing docs from previous PRs
