e-breuninger/terraform-provider-netbox

netbox/data_source_netbox_virtual_machines.go
netbox/data_source_netbox_virtual_machines_test.go
netbox/provider.go

Add 'virtual machines' as a data source.
I'm using this provider to extract information from Netbox, and use that to configure a RHEV/oVirt virtualisation platform - this was a necessary addition.
If someone provides docs about your test data set, I'm happy to add tests for this PR.

Add virtual machines data source

---

netbox/client.go

If netbox runs on a sub-Path (https://my.host.name/netbox/), this path has to be handed over to the netbox client module in order to successfully connect to the netbox instance.

Honor Sub-Paths in netbox URL

---

netbox/resource_netbox_prefix.go
netbox/resource_netbox_prefix_test.go

Hi,
After importing the resources, terraform plan want to update prefix, status and tags altough there are already set on netbox.
```
$ terraform import netbox_prefix.ip_10_47_3_0 2                                                                                                                               
netbox_prefix.ip_10_47_3_0: Importing from ID "2"...                                                                                                                                                                                          
netbox_prefix.ip_10_47_3_0: Import prepared!                                                                                                                                                                                                  
Prepared …
```

fix(netbox_prefix): attributes are not properly read

---

netbox/resource_netbox_prefix.go
netbox/resource_netbox_prefix_test.go

Note: This PR is based on https://github.com/e-breuninger/terraform-provider-netbox/pull/60
Adding the support for vrf & tenant for the `netbox_prefix`
```
resource "netbox_prefix" "test" {                                                                                                                                                                                                             
prefix = "192.168.1.1/24"                                                                                                                                                                                                                               
description = "a prefix" …
```

feat(netbox_prefix): attaching prefix to vrf and tenant 

---

README.md

since sometimes test failures are due to stale netbox data volumes.  Addresses issue #100

Testing: added guidance for refreshing containers 

---

go.mod
go.sum
netbox/data_source_netbox_tag.go
netbox/resource_netbox_tag.go
netbox/resource_netbox_tag_test.go

This PR adds the `description` attribute to the `netbox_tag` resource.
Example:
```terraform
resource "netbox_tag" "tf_managed" {
name        = "Managed by Terraform"
slug        = "managed-by-terraform"
description = "Terraform provider: github.com/e-breuninger/terraform-provider-netbox"
}
```
I have tested it against a Netbox instance (not yet with the acceptance tests) and I noticed that the description can be set and updated, but not removed. It seems that the Netbox API ignores the empty field.

add description attribute to tag resource

---

CHANGELOG.md
GNUmakefile
README.md
netbox/provider.go
netbox/resource_netbox_available_prefix_test.go

Validated against Netbox 3.1.3.  One test was failing due to changed error message language.  Updated minor version to reflect new NetBox API version.

Validate against Netbox 3.1.3 and update failing test

---

netbox/data_source_netbox_prefix.go
netbox/resource_netbox_available_prefix.go
netbox/resource_netbox_available_prefix_test.go
netbox/resource_netbox_prefix.go
netbox/resource_netbox_prefix_test.go

This small patch simply add the mark_utilized parameter for available_prefix resource. Changes in data source are only to make my linter happy :)

Support mark_utilized in available_prefix resource

---

netbox/client.go
netbox/client_test.go
netbox/provider.go

We expose our Netbox instances through a [Google Cloud IAP](https://cloud.google.com/iap) which allows us to publish them to the internet while having strict control over which identity may connect to the service. To make this work nicely with Netbox, we have a custom remote auth middleware that validates the ID tokens issued by the IAP and binds them to Netbox users.
For this to work in a headless process, an additional header has to be attached to every request sent to Netbox. The `Proxy-Authorization` header contains the ID token of the principle that should be able to pass the IAP. The IAP then generates a new ID token for that principle that is handed to Netbox.
This Terraform provider currently does not support the definition of additional headers that should be attached to every …

Add ability to attach custom headers to every request

---

netbox/resource_netbox_virtual_machine.go
netbox/resource_netbox_virtual_machine_migrate_v0.go
netbox/resource_netbox_virtual_machine_migrate_v0_test.go

The type change from `string` to `float` for `vm.vcpus` introduced with https://github.com/e-breuninger/terraform-provider-netbox/pull/92 breaks existing state if `vcpus` in the existing state is `""`:
> │ Error: Failed to decode resource from state
> │
> │ Error decoding "netbox_virtual_machine.this" from previous state: a number is required
This PR bumps the schema version for `resourceNetboxVirtualMachine` to `1` and introduces a `StateUpgrader` that will gracefully upgrade the state, even if the value already is a float.
Further reading:
- https://www.terraform.io/plugin/sdkv2/resources/state-migration#resources-state-migration

Add state migration for vm.vcpus

---

netbox/provider.go
netbox/provider_test.go

Hi folks!
While writing tests and run `make testacc` I forgot to change the URL in my local provider configuration and the provider crashes with a SIGSEGV. Some other users already reported this issue (https://github.com/e-breuninger/terraform-provider-netbox/issues/110). 
Cheers

🐛 Fix provider crash when netbox connection is unavailable

---

.github/workflows/ci-testing.yml
GNUmakefile
docker/docker-compose.yml

Successor of #88 
For now only one version. I tried to test with a v3.0 but this is not compatible because of the missing `available_prefix` feature.
Maybe we should implement some kind of feature flag to detect which tests can run from which Netbox version. 
Simple approach for now to get started.

Add matrix build

---

docs/resources/interface.md
examples/resources/netbox_interface/resource.tf
netbox/resource_netbox_interface.go
netbox/resource_netbox_interface_test.go
netbox/util.go

To be more precise `netbox_interface` resource now knows how to handle following attributes:
- enabled
- mtu
- mode, tagged_vlans, untagged_vlan
**Note for reviewer**: This includes changes from https://github.com/e-breuninger/terraform-provider-netbox/pull/184 , please see that first.

Add VLAN tagging support to interfaces

---

netbox/data_source_netbox_cluster.go
netbox/data_source_netbox_cluster_test.go
netbox/tags.go

This added the Feature netbox_cluster enhanced data response #251 
This will make the changes that 3.x breaks on vms when where you need to set both cluster_id and site_id

[feature request] to make it easier to use 3.x breaking changes to vm #251

---

netbox/data_source_netbox_devices_test.go
netbox/provider_test.go

TestAccNetboxProviderConfigure_failure was itself failing as the output can return 
```
tcp: lookup fake.netbox.server on X.X.X.X: no such host
```
in some setups, where X.X.X.X is your DNS server

fix: Add tests for platform on devices, and fix one failing test

---

docs/data-sources/tenant.md
docs/index.md
docs/resources/tenant.md
netbox/data_source_netbox_tenant.go
netbox/data_source_netbox_tenant_test.go
netbox/resource_netbox_tenant.go
netbox/resource_netbox_tenant_test.go

Adds a new description field (optional) to resource "netbox_tenant".
Follows similar logic to the existing "netbox_tenant_group" resource.

Add description field to tenant resource and data source.

---

.gitignore
docs/data-sources/vlan.md
examples/data-sources/netbox_vlan/data-source.tf
netbox/data_source_netbox_tenant.go
netbox/data_source_netbox_vlan.go
netbox/data_source_netbox_vlan_test.go

Previously only name and VID could be used to filter responses for `netbox_vlan` data source. This PR allows to filter VLANs by VLAN group, IPAM role, or tenant.
There isn't yet a resource for creating VLAN groups, and thus there's a lack of test coverage for that attribute.

Enable group, role, or tenant to be used in VLAN query

---

netbox/data_source_netbox_region.go

Fixes #301 
I think the slug should also reference the slug instead of the name.
I checked the region model in the source [go module](https://github.com/fbreckle/go-netbox/blob/master/netbox/models/region.go#L85) the field should be called `Slug`

fix: Region data-source fix slug field reference

---

netbox/resource_netbox_site.go
netbox/resource_netbox_site_test.go

Currently, site that has been previously configured with a description can no longer be cleared out. Even if the terraform configuration indicates empty or nil description, the change will not be persisted to NSOT. Additionally, every time a terraform plan is run, it will always detect an update-in-place for this field.
This change fixes this behavior by setting site description's to space character. This is based on the pattern on other existing resource such as network device.
References:
- https://github.com/fbreckle/go-netbox/pull/25
- https://github.com/e-breuninger/terraform-provider-netbox/blob/master/netbox/resource_netbox_device.go#L331

:sparkles: Allow empty site description

---

netbox/resource_netbox_site.go

In line with Netbox's site slug max limit of 100, adjust the site resource slug max limit from 30 to 100.
Reference:
- https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/models/sites.py#L149

:wrench: Adjust site slug max length

---

netbox/resource_netbox_interface.go

Forcing the replacement of the entire interface if the mac address changes causes weird issues with AWS. Sometimes the underlying mac address will change. When we force the replacement of this interface everything that uses this interface is getting replaced and it's causing data inconsistency.

MAC Addresses are not always a fixed entity

---

docs/data-sources/devices.md
docs/resources/device.md
docs/resources/ip_address.md
docs/resources/site.md
netbox/resource_netbox_ip_address.go
netbox/resource_netbox_ip_address_test.go

Adds a new field object_type to the device ip address resource that allows to select device or virtualmachine as device type to support ip address configuration for devices.

:sparkles: Add support for device ip addresses

---

docs/data-sources/prefixes.md
netbox/data_source_netbox_prefixes.go
netbox/data_source_netbox_prefixes_test.go

This PR adds support for using `tag` and `status` values as filters for the existing `netbox_prefixes` data source.
This PR also suggests removing the requirement that the data source must return at least 1 prefix as a result, and instead allows it to support returning 0 results:
```go
if *res.GetPayload().Count == int64(0) {
return errors.New("no result")
}
```
There seems to be some inconsistency across the data sources in regards to this behavior - some data sources support returning 0 results, and others don't.
I'll defer to the maintainers on whether or not we can remove the above check, but IMO, the provider should not error out of a plan just because a particular data source might return 0 results (especially since the Netbox API itself support this).
If a user has a requirement …

Support tag and status filters for netbox_prefixes data source

---

netbox/data_source_netbox_prefixes.go
netbox/data_source_netbox_prefixes_test.go

This fixes the issue documented in #365 
The problem was an incorrect attempt to get a float from a string. The fix was to add a string conversion to float.

Fix crash with netbox_prefixs filtered by VLAN VID

---

netbox/resource_netbox_prefix.go
netbox/resource_netbox_prefix_test.go

This PR fixes an issue whereby removing the description of an IP Prefix had no effect when applied. 
This will set the description to a single space (`" "`) if the description is passed in as `null`. Setting the description to an empty string also does not appear to clear the description, so this uses the same pattern as in the IP Address resource type.

Remove IP Prefix description if it is null

---

netbox/resource_netbox_virtual_machine.go
netbox/tags.go

There has been no error or check to determine if a tag exists already or not. This causes the terraform to always try to make a change if the tag does not exist, since there's no indication that the lookup didn't find anything.
This is helpful, since it provides feedback to the user that the associated tag does not exist, and needs to be added with the `netbox_tag` resource.
Since there are a lot of resources that use tags, we are only activating this feature on the netbox_virtual_machine resource to start. It can be added to other resources by returning the diag and appending it to the return of the function.

fix: Add error to tags lookup if tag does not exist

---

docs/data-sources/prefixes.md
netbox/data_source_netbox_prefixes.go
netbox/data_source_netbox_prefixes_test.go

We need the ability to filter prefixes on their site_id. This adds the functionality that is documented in netbox here: http://localhost:8001/api/schema/swagger-ui/#/ipam/ipam_prefixes_list

Support site_id as filter type for data_source_netbox_prefixes

---

netbox/client.go
netbox/client_test.go
netbox/data_source_netbox_asns.go
netbox/data_source_netbox_devices.go
netbox/data_source_netbox_interfaces.go
netbox/data_source_netbox_ip_addresses.go
netbox/data_source_netbox_prefix_test.go
netbox/data_source_netbox_prefixes.go
netbox/data_source_netbox_racks.go
netbox/data_source_netbox_tenants.go
netbox/data_source_netbox_virtual_machines.go
netbox/provider.go
netbox/resource_netbox_route_target_test.go

Found several issues that the [go-staticcheck](https://staticcheck.io/) linter is complaining about.
---
Getting the following error from `go-staticcheck` linter:
```
resource.UniqueId is deprecated: Use helper/id package instead.
This is required for migrating acceptance testing to
terraform-plugin-testing.  (SA1019)
```
This changes all instances of resource.UniqueId() with the suggested
`id.UniqueId()` function with the same functionality.
All acceptance tests are still passing.
---
The `Client()` function was returning an `interface{}` which
required casting to `*netboxclient.NetBoxAPI` in the `providerConfigure`
function, which is not necessary. `providerConfigure()` can take the
`*netboxclient.NetBoxAPI` type as it's return, since it takes an
`interface{}`.
---
Removed unused …

Go staticcheck fixes

---

docs/resources/virtual_machine.md
examples/resources/netbox_virtual_machine/resource.tf
netbox/resource_netbox_virtual_machine.go
netbox/resource_netbox_virtual_machine_test.go

Originally checked in under another pull request, this is the newly entered change complete with documentation and testing. The tests have passed and the documentation follows current standards. There is no "DataSource" update because the data source already has "local_context_data".
Modifications elsewhere in the file are from a "make fmt" run that was done before check-in.

Add local_context_data to virtual machines

---

netbox/provider.go
netbox/resource_netbox_device_primary_ip.go
netbox/resource_netbox_device_primary_ip_test.go

In a similar way as netbox_device_interface, add a dedicated resource to be able to set the primary ipv4/6 address on devices.
This resource is mostly a copy of the netbox_primary_ip resource, but adjusted for devices.

feat: support primary ips for devices

---

docs/data-sources/prefix.md
netbox/data_source_netbox_prefix.go
netbox/data_source_netbox_prefix_test.go

Adds the ability for the `netbox_prefix` data source to filter by IP family (v4 or v6)
fix #398

feat: add family filter to netbox_prefix data source

---

go.mod
go.sum
netbox/resource_netbox_permission.go
netbox/resource_netbox_permission_test.go

Every run of the `netbox_permission` resource when there was no
constraint set would output the following diff:
```
netbox_permission.ipaddress_rw_permission will be updated in-place
~ resource "netbox_permission" "ipaddress_rw_permission" {
- constraints  = "null" -> null
id           = "3"
name         = "ipaddress_rw_permissions"
```
There are inherently two issues that cause the problem. We cannot null
the field, because of the issue fixed here:
https://github.com/fbreckle/go-netbox/pull/30
Second, want the constraint field to be set to an empty string when
a read of constraint is empty. So we check if nil, and if so we
set constraint to "", and then return the function. Otherwise, we
Marshal it to JSON to fill the tf state.

fix: netbox_permission plan constraint diff

---

netbox/resource_netbox_ip_address.go

Fix wrong attribute used to set deviceInterfaceId

fix: set deviceInterfaceId from device_interface_id

---

netbox/resource_netbox_primary_ip.go
netbox/resource_netbox_primary_ip_test.go

When the local context was added to the vm resource, the fields were not added to the primary ip update function, which caused the local context field to be unset when the `resource_netbox_primary_ip` resource was used.

fix: add vm context field to primary_ip update func

---

docs/data-sources/cluster.md
docs/data-sources/devices.md
docs/data-sources/virtual_machines.md
docs/resources/cluster.md
docs/resources/device.md
docs/resources/virtual_machine.md
netbox/data_source_netbox_cluster.go
netbox/data_source_netbox_cluster_test.go
netbox/data_source_netbox_devices.go
netbox/data_source_netbox_devices_test.go
netbox/data_source_netbox_virtual_machines.go
netbox/resource_netbox_cluster.go
netbox/resource_netbox_cluster_test.go
netbox/resource_netbox_device.go
netbox/resource_netbox_device_test.go
netbox/resource_netbox_primary_ip.go
netbox/resource_netbox_virtual_machine.go
netbox/resource_netbox_virtual_machine_test.go

We were missing the ability to add a descriptions to devices, VMs, and
clusters. There are also corresponding data sources that do not have the
description field.
These fields were not available prior to netbox 3.4.3.
This adds the description field, following the example of the comment
field. The code was also slightly modified to be simpler to understand.

Add description field to VMs, Devices, Clusters Resource/Data

---

netbox/resource_netbox_device_interface.go
netbox/resource_netbox_device_interface_test.go
netbox/resource_netbox_interface.go

Since Netbox always converts MAC addresses to uppercase representation, this provider thinks there is an actual change and tries to recreate the interface, when given a lowercase MAC address.
By suppressing the diff, we ignore the diff for lowercase inputs.

Make MAC address checking case insensitive

---

netbox/resource_netbox_device_interface.go

Forcing the recreating on device interface when the MAC is change causes all attached cables to be lost and is unnecessary.

Do not force recreation of device interface on MAC change

---

netbox/resource_netbox_custom_field.go
netbox/resource_netbox_custom_field_test.go

Terraform validate currently only allows the labelJSON on custom_fields, which is 'JSON'. See example below:
```
$ terraform validate
│ Error: expected type to be one of [text integer boolean date url select multiselect JSON], got json
│ 
│   with netbox_custom_field
```
But the actual netbox API when deploying a custom_field is expecting the valueJSON 'json'. See example below:
```
│ Error: [POST /extras/custom-fields/][400] extras_custom-fields_create default  map[type:[JSON is not a valid choice.]]
│ 
│   with module.am_netbox_tenants.netbox_custom_field,
```
Looking also at the other validators on L36-L42, this seems like a typo/mistake

Fix validate custom_field on JSON value instead of label

---

docs/resources/device.md
netbox/resource_netbox_device.go
netbox/resource_netbox_device_test.go

This PR adds `asset_tag` to `netbox_device`. It also adds tests.
This PR replaces #373 
Fixes #353

Add asset tags to netbox_device

---

docs/resources/device_interface.md
netbox/resource_netbox_device_interface.go
netbox/resource_netbox_device_interface_test.go

This adds multiple useful fields to netbox_device_interface.

Feature fields interfaces

---

netbox/data_source_netbox_ip_addresses.go
netbox/data_source_netbox_ip_addresses_test.go

A few Netbox attributes which are available to filter on was missing in this check.
This PR allows more attributes to be filtered on, which improves the usability of this data resource.

feat: add more filters on netbox_ip_addresses data resource

---

netbox/data_source_netbox_available_prefix.go
netbox/data_source_netbox_available_prefix_test.go
netbox/provider.go

This DS Feature makes users able to get available prefix's in a parent prefix.

Implement DS Get /ipam/prefix/available-prefixes

---

docs/resources/device.md
examples/resources/netbox_device/resource.tf
netbox/resource_netbox_device.go
netbox/resource_netbox_device_test.go

add local_context_data to device resource

---

docs/resources/device.md
netbox/resource_netbox_device.go
netbox/resource_netbox_device_test.go
netbox/resource_netbox_virtual_chassis.go

This allows a device to be marked as part of a virtual chassis, it's position, priority, and whether it's the master or not.
Setting the master is done on the device itself to avoid circular dependencies (the device needing to know the virtual cluster and the cluster needing to know a device to set as master).
Updating the master device of a virtual chassis is ideally done with a PATCH request where only the id and the master are provided, but `WritableVirtualChassis` struct does handle that properly:
1. `Master` is a pointer with `omitempty` set, so you cannot send a json `null` value to remove it
2. `Name` and `Tags` do not have `omitempty`, so you always have to provide values for them (otherwise the API complains)
So for now, the entire virtual chassis is retrieved and updated with …

feat: support setting virtual_chassis on device

---

netbox/resource_netbox_device.go
netbox/resource_netbox_device_test.go

When updating an existing device, it tries to set the device as a master before updating the device to be part of a virtual chassis. This results in the error:
```
The selected master (test-device_virtual_chassis-opff9n4aao) is not assigned to this virtual chassis.
```
Fix this by updating the device before updating the master status on the virtual chassis.

fix: set virtual chassis master after setting vc

---

netbox/data_source_netbox_virtual_machines.go
netbox/data_source_netbox_virtual_machines_test.go

Allows filtering `vms` by `tenant_id`.
Similar like this providers does many other places.
A tiny refactor on the switch case also.

feat: allow filtering vms by tenant_id

---

netbox/data_source_netbox_ip_addresses.go
netbox/data_source_netbox_ip_addresses_test.go

Allow filtering by `tag` on the `netbox_ip_addresses` data source.

feat: add filter by tag on ip_addresses data source

---

netbox/data_source_netbox_site.go

We have an issue when trying to reference the name of a site from a data source lookup, where the site name is null during a plan.
This causes issues for templating fields, as we get the following error:
```sh
Error: Invalid template interpolation value
│
│   on .terraform/module/main.tf line 53, in data "netbox_prefixes" "this":
│   53:       error_message = "The site provided with name ${data.netbox_site.this.name} does not contain any prefixes."
│     ├────────────────
│     │ data.netbox_site.this.name is null
│
│ The expression result is null. Cannot include a null value in a string
│ template.
```
This happens because some of the fields that are optional and can be used for lookup of the site are not set as computed. This leads to a data structure that looks like below during the …

fix: make site data_source optional fields computed

---

netbox/data_source_netbox_asn.go
netbox/data_source_netbox_asn_test.go
netbox/data_source_netbox_cluster_group.go
netbox/data_source_netbox_cluster_type.go
netbox/data_source_netbox_contact.go
netbox/data_source_netbox_contact_group.go
netbox/data_source_netbox_contact_role.go
netbox/data_source_netbox_device_role.go
netbox/data_source_netbox_device_type.go
netbox/data_source_netbox_device_type_test.go
netbox/data_source_netbox_ip_range.go
netbox/data_source_netbox_ipam_role.go
netbox/data_source_netbox_location.go
netbox/data_source_netbox_platform.go
netbox/data_source_netbox_prefix.go
netbox/data_source_netbox_rack_role.go
netbox/data_source_netbox_region.go
netbox/data_source_netbox_route_target.go
netbox/data_source_netbox_site.go
netbox/data_source_netbox_site_group.go
netbox/data_source_netbox_site_test.go
netbox/data_source_netbox_tag.go
netbox/data_source_netbox_tenant.go
netbox/data_source_netbox_tenant_group.go
netbox/data_source_netbox_vlan.go
netbox/data_source_netbox_vlan_group.go
netbox/data_source_netbox_vlan_group_test.go
netbox/data_source_netbox_vlan_test.go
netbox/data_source_netbox_vrf.go

Many of the data sources are configured to only return one object, based on a filter. This change aims to improve the error messages that are returned by these objects.
Specifically, we want to make the return to be more than just `Error: no result`, which would make it more clear what was actually wrong for less familiar users.
By having a consistent error across these resources, it's easier for others to understand going forward.

fix: add better error handling for one object data sources

---

netbox/resource_netbox_device_test.go
netbox/resource_netbox_virtual_chassis.go

An error occurs when we update the virtual chassis to set the master position. The function that updates the master reads the API to get the current values of the virtual chassis. The tag object that is received includes values that are not expected to be sent on a PUT to the API. This commit modifies the virtual chassis update code so that only the expected values for tags are sent, the rest of the values are either zero-ed out or nullified.
This only seems to happen when a virtual chassis has a tag.
Error message:
```
Error: [PUT /dcim/virtual-chassis/{id}/][400] dcim_virtual-chassis_update
default  map[tags:[[Cannot resolve keyword 'display' into field.
Choices are: aggregate, asn, asnrange, cable, circuit, circuittermination,
circuittype, cluster, clustergroup, clustertype, color, …
```

Fix Virtual Chassis Master Update Function for Tag Input

---

docs/data-sources/location.md
docs/data-sources/locations.md
docs/resources/location.md
go.mod
go.sum
netbox/data_source_netbox_location.go
netbox/data_source_netbox_location_test.go
netbox/data_source_netbox_locations.go
netbox/data_source_netbox_locations_test.go
netbox/resource_netbox_location.go
netbox/resource_netbox_location_test.go

Hello there! 
We actively use Location nesting. And I really miss the ability to read and write the “parent_id” value in a DCIM model resource Location.
This PR is about the same as in #508. 
PTAL.

feature: add field 'parent_id' to Location Resource & Data Source

---

docs/resources/prefix.md
netbox/resource_netbox_prefix.go
netbox/resource_netbox_prefix_test.go

Add custom field support in IPAM Prefix
```
TEST_FUNC=TestAccNetboxPrefix_basic make testacc-specific-test
⌛ Startup acceptance tests on http://localhost:8001 with version v3.7.1
⌛ Testing function TestAccNetboxPrefix_basic
TF_ACC=1 go test -timeout 20m -v -cover netbox/*.go -run TestAccNetboxPrefix_basic
=== RUN   TestAccNetboxPrefix_basic
=== PAUSE TestAccNetboxPrefix_basic
=== CONT  TestAccNetboxPrefix_basic
--- PASS: TestAccNetboxPrefix_basic (13.82s)
PASS
coverage: 9.0% of statements
ok  	command-line-arguments	15.227s	coverage: 9.0% of statements
```

Add custom field support in IPAM Prefix

---

docs/resources/virtual_disk.md
netbox/resource_netbox_virtual_disk.go
netbox/resource_netbox_virtual_disk_test.go

@Ikke I just realized (after merging :grimacing: ) that the size attribute did not have a unit suffix. From a user perspective, I find it very convenient when I do not have to wonder "ok and what unit is this exactly?" when using a resource. I did the same in the virtual machine resource itself, which also makes this consistent.

chore: specify disk size unit in virtual disk resource

---

docs/resources/rir.md
netbox/resource_netbox_rir.go
netbox/resource_netbox_rir_test.go

Adds the `is_private` field to rirs. However the test don't pass as it seems there's a bug in go-netbox (i tested it separately) . I can successfully add a rir with `is_private` set to true or false, I can update it from false to true, but nothing happens when trying to update it from true to false.

feat: add 'is_private' field to 'netbox_rir' resource

---

netbox/data_source_netbox_prefix.go
netbox/data_source_netbox_prefix_test.go

This PR contains two bits of work related to `data.netbox_prefix`.
1. Adds `role_id` as a field returned by `data.netbox_prefix`, and allows searching by `role_id`.
2. Return any `custom_fields` defined on `data.netbox_prefix`
Thanks!

`data.netbox_prefix`: add custom fields and role_id

---

docs/data-sources/platform.md
docs/resources/platform.md
netbox/data_source_netbox_platform.go
netbox/data_source_netbox_platform_test.go
netbox/resource_netbox_platform.go
netbox/resource_netbox_platform_test.go

Add manufacturer_id to `netbox_platfrom` data and resource blocks.
Just trying to add stuff as I come across it missing :sweat_smile: 
Let me know if any changes are required, thanks!

Add manufacturer_id to `netbox_platform` data and resource blocks

---

netbox/resource_netbox_vpn_tunnel_termination.go
netbox/resource_netbox_vpn_tunnel_termination_test.go

Fixes this crash that i was able to reproduce in a regression test:
```
=== CONT  TestAccNetboxVpnTunnelTermination_basic
panic: interface conversion: interface {} is int, not int64
goroutine 1944 [running]:
github.com/e-breuninger/terraform-provider-netbox/netbox.resourceNetboxVpnTunnelTerminationUpdate(0x14000894c00, {0x105c46d60, 0x14000023290})
/Users/marcus/src/ffddorf/terraform-provider-netbox/netbox/resource_netbox_vpn_tunnel_termination.go:143 +0x434
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x105f73320?, {0x105f73320?, 0x14000a80f30?}, 0xd?, {0x105c46d60?, 0x14000023290?})
/Users/marcus/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:828 +0x130 …
```

Fix type conversion on ID when updating tunnel termination

---

netbox/data_source_netbox_prefixes.go
netbox/data_source_netbox_prefixes_test.go

[Add contains filter to data_source_netbox_prefixes](https://github.com/e-breuninger/terraform-provider-netbox/pull/617/commits/ae3654259181e2cf86238f86c3053322ec21dc84) 
It is helpful to be able to look up the prefix by an IP address within
the prefix. The contains filter can be used for this.
If you specify an IP within a prefix, it will return that prefix.
[Add site_id as a returned field to netbox_prefixes data source](https://github.com/e-breuninger/terraform-provider-netbox/pull/617/commits/ac1fbfbb73e7f80dd20986431f04b732f12ea93d) 
It can be helpful to know the ID of the site that the prefixes are
assigned to. This allows us to reference it within in our TF code.

Add contains filter and field to data_source_netbox_prefixes

---

netbox/data_source_netbox_devices.go

This change introduces the device_type_id parameter to the Netbox devices data source. It allows users to filter devices based on their type, providing more granular control over the data retrieved.
```hcl
data "netbox_devices" "VSS" {
filter {
name  = "cluster_id"
value = data.netbox_cluster.vm_cluster.cluster_id
}
filter {
name  = "device_type_id"
value = data.netbox_device_type.VSS.id
}
filter {
name  = "tags"
value = "managed_by_terraform"
}
filter {
name  = "status"
value = "active"
}
}
```
Now it is possible to filter Netbox devices based on `device_id_type`. This could be usefully to create other resources with terraform.

Add support for device_type_id in data source

---

netbox/data_source_netbox_vlans.go

I would like to filter 
```hcl
data "netbox_vlans" "vlans" {
filter {
name  = "status"
value = "active"
}
}
```
```shell
Changes to Outputs:
+ vlans = [
+ {
+ description = "Demo Test Group"
+ group_id    = 0
+ name        = "DEMO_TEST"
+ role        = 0
+ site        = 1
+ status      = "active"
+ tenant      = 0
+ vid         = 2
},
]
```

Add support for VLAN 'status' filter parameter

---

netbox/resource_netbox_device.go
netbox/resource_netbox_device_primary_ip.go
netbox/resource_netbox_device_primary_ip_test.go

The netbox_device_primary_ip was badly implemented, by using a device update call assigning each parameter of a device one by one, even if it needs to add only two parameters. Thus if one adds a new parameter to the netbox_device resource (e.g. #604), the parameter should also be added to the netbox_device_primary_ip, even though there is no logical link between the two.
To fix this, I simply changed from an update to a partial update call, to avoid overriding any data.

fix: avoid override of device's values on primary ip creation and update

---

netbox/client.go

"http_proxy", "https_proxy", and "no_proxy" environment variables are now supported.

add http proxy support

---

docs/resources/ip_address.md
netbox/resource_netbox_ip_address.go
netbox/resource_netbox_ip_address_test.go

Adds custom fields support to IPAM IP address. Highly based on #553
```
TF_ACC=1 go test -timeout 20m -v -cover netbox/*.go -run TestAccNetboxIPAddress_basic
=== RUN   TestAccNetboxIPAddress_basic
=== PAUSE TestAccNetboxIPAddress_basic
=== CONT  TestAccNetboxIPAddress_basic
--- PASS: TestAccNetboxIPAddress_basic (11.46s)
PASS
coverage: 8.9% of statements
ok      command-line-arguments  12.088s coverage: 8.9% of statements
```

Add custom fields support in IPAM IP address.

---

netbox/resource_netbox_service.go
netbox/resource_netbox_service_test.go

added fields in netbox_service:
- device_id
- tags
- description
a service can now be assigned to a virtual machine or a device, but not both.
tests are also added for the device_id, tags and description for a service.

added fields: "device_id", "description" and "tags" in netbox_service

---

docs/resources/virtual_disk.md
examples/resources/netbox_virtual_disk/resource.tf

Hello just a little error on the documentation in https://registry.terraform.io/providers/e-breuninger/netbox/latest/docs/resources/virtual_disk
between the examples and the schema.
Have good day.

Update documentation for virtual_disk with correct schema

---

netbox/resource_netbox_custom_field.go
netbox/resource_netbox_custom_field_test.go

Fixes #635: Added missing Default to data in resourceNetboxCustomField and resourceNetboxCustomFieldCreate
default value is now created correctly:
```
{
...
"id": 1,
"url": "http://localhost:8001/api/extras/custom-fields/1/",
"display": "test",
...
"data_type": "string",
"name": "test",
"label": "test",
...
"default": "\"default value ignored\"",
"weight": 100,
...
}
]
}
```
UI screenshot:

Fixes #635: added missing Default

---

docs/resources/asn.md
docs/resources/config_context.md
docs/resources/interface_template.md
examples/resources/netbox_asn/resource.tf
examples/resources/netbox_config_context/resource.tf
examples/resources/netbox_interface_template/resource.tf
netbox/resource_netbox_asn.go
netbox/resource_netbox_asn_test.go

This PR adds the `description` and `comments` fields to the `netbox_asn` resource as optional attributes.
This also includes some changes to unrelated docs and examples which occurred as the results of running a `terraform fmt --recursive` on the example directory.

feat: Add Description & Comments Field To ASN Resource

---

docs/data-sources/prefix.md
docs/data-sources/prefixes.md
netbox/data_source_netbox_prefix.go
netbox/data_source_netbox_prefix_test.go
netbox/data_source_netbox_prefixes.go
netbox/data_source_netbox_prefixes_test.go

This PR enhances the `netbox_prefix` and `netbox_prefixes` datasources by adding support for the `tenant_id` and `status` filter parameters. This aligns the datasources with the existing `netbox_prefix` and `netbox_available_prefix` resources, ensuring a 1:1 relationship between resource creation and search capabilities. Relevant tests have been updated to validate the functionality of the new options.

feat: add tenant_id and status filters to prefix and prefixes datasources

---

docs/resources/device.md
netbox/resource_netbox_device.go

Add the missing 'decommissioning' status to the `netbox_device` resource, so we can keep track in NetBox of devices in the process of being removed from the racks. Once the device is really physically removed from the rack we can remove it from terraform, which will cleanup NetBox in response.
`api/schema/swagger-ui/#/dcim/dcim_devices_create`:
Seems to have been added a while ago in NetBox 2.5.11 ([changelog](https://github.com/netbox-community/netbox/blob/e75d327f384d0b22ffb17f7e790d953ac81530ca/docs/release-notes/version-2.5.md?plain=1#L48C11-L48C65) / [issue](https://github.com/netbox-community/netbox/issues/3070))

fix: add decommissioning status for devices

---

netbox/data_source_netbox_device_interfaces.go

Add limit as implemented in devices data source.
Testing:
Local - appears to ignore all outputs after first 1k despite
setting to 10k, otherwise works

Add limit to device_interfaces data source

---

docs/data-sources/devices.md
go.mod
go.sum
netbox/data_source_netbox_devices.go

Depends on https://github.com/fbreckle/go-netbox/pull/47
Data source parity for #538, `go-netbox` PR might address predicate requirement for that too.
Testing:
See notes in other PR - "seems to work fine"

Devices data-source: read OobIp

---

netbox/resource_netbox_available_ip_address.go

**Changes:**
- `netbox_available_ip_address`
- Added proper error handling for both prefix and IP range API calls
- Added checks for empty payload when no IP addresses are available
- Imported fmt for error messages
- Now returns a clear error message instead of panicking
**Fixes:** #103

Ensure plugin not to crash when no available IP

---

docs/data-sources/prefixes.md
netbox/data_source_netbox_prefixes.go
netbox/data_source_netbox_prefixes_test.go

The provider is missing the ability to filter by description from the `netbox_prefixes` `data` so this just does that.

Add description filter to data netbox_prefixes
